project:
  type: book

book:
  title: "OS Notes"
  author: "Igor Dimitrov"
  date: "7/17/2025"
  chapters:
    - reading.qmd
    - index.qmd
  page-navigation: true
  downloads: pdf

# bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



